# Server
# server.port=8080

# # MySQL connection
# spring.datasource.url=jdbc:mysql://localhost:3306/safety_compliance_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=Nivetha2501
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# # LLM API Keys
# gemini.api.key=AQ.Ab8RN6IXWqtsZPnQ5AH_2IkljKKFaSzALQJS7wGnAez2NTMSaQ
# anthropic.api.key=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
# Server
# server.port=${PORT:8080}

# # MySQL connection
# spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/safety_compliance_db?useSSL=false&serverTimezone=UTC}
# spring.datasource.username=${DB_USERNAME:root}
# spring.datasource.password=${DB_PASSWORD:Nivetha2501}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # API Keys
# gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6IXWqtsZPnQ5AH_2IkljKKFaSzALQJS7wGnAez2NTMSaQ}
# anthropic.api.key=${ANTHROPIC_API_KEY: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}



# server.port=${PORT:8080}

# spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/safety_compliance_db?useSSL=false&serverTimezone=UTC}
# spring.datasource.username=${DB_USERNAME:root}
# spring.datasource.password=${DB_PASSWORD:Nivetha2501}
# spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6IXWqtsZPnQ5AH_2IkljKKFaSzALQJS7wGnAez2NTMSaQ}
# anthropic.api.key=${ANTHROPIC_API_KEY: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}

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/safety_compliance_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY:}
anthropic.api.key=${ANTHROPIC_API_KEY:}